FROM apache/spark:3.5.8-python3

USER root
RUN pip3 install --no-cache-dir neo4j==5.27.0 python-dotenv==1.0.1 \
 && mkdir -p /tmp/ivy/cache \
 && chown -R 185:185 /tmp/ivy

WORKDIR /app
COPY . .
RUN chown -R 185:185 /app

USER 185